
-- Find the item that has min weight.
SELECT * FROM ITEMS WHERE WEIGHT = (SELECT MIN(WEIGHT) FROM ITEMS);

-- Find the different warehouses in “Pune”.
SELECT * FROM WAREHOUSES WHERE CITY_ID = (SELECT CITY_ID FROM CITIES WHERE CITY = "Pune");

-- Find the details of items ordered by a customer “Mr. Patil”.
SELECT * FROM ITEMS WHERE ITEM_ID IN (
    SELECT ITEM_ID FROM ITEMS_ORDERS WHERE ORDER_ID IN (
        SELECT ORDER_ID FROM ORDERS WHERE CUSTOMER_ID = (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_NAME = "Mr. Patil")
    )
);

-- Find a Warehouse which has max stores.
SELECT * FROM WAREHOUSES WHERE WAREHOUSE_ID = (
	SELECT WAREHOUSE_ID FROM STORES GROUP BY WAREHOUSE_ID ORDER BY COUNT(*) DESC LIMIT 1
) LIMIT 1;

-- Find an item which is ordered for a min number of times.
SELECT * FROM ITEMS WHERE ITEM_ID = (
    SELECT ITEM_ID FROM ITEMS_ORDERS GROUP BY ITEM_ID ORDER BY COUNT(*) LIMIT 1
) LIMIT 1;

-- Find the detailed orders given by each customer.
SELECT C.CUSTOMER_NAME, I.DESCRIPTION, I.WEIGHT, I.COST, O.ORDER_DATE, C.CUSTOMER_CITY FROM ORDERS O
INNER JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
INNER JOIN ITEMS_ORDERS IOS ON IOS.ORDER_ID = O.ORDER_ID
INNER JOIN ITEMS I ON I.ITEM_ID = IOS.ITEM_ID;

